; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./
include_dir = ./Core/Inc
default_envs = H743_Debug

[env]
platform = ststm32
; board = weact_mini_h743vitx
board =  devebox_h743vitx
framework = stm32cube
;produce hex file
extra_scripts = ./Tools/post_script.py
;monitor setting
; monitor_port = /dev/tty.usbserial-1130
monitor_speed = 115200
upload_protocol = jlink


[env:H743_Debug]
build_type = debug
debug_tool = jlink
build_unflags = -Os
debug_build_flags =
    -O0
    -g3
    -ggdb3
    -std=c++1z
; debug_speed = 4000s

[env:H743_Release]
build_type = release
build_flags =
    -O3
    -std=c++1z
; build_unflags = -Os